### ISSUE TITLE
It shows same 10 results for all queries 

### ISSUE THREAD

**Issue by hkmsadek** [elastic/search-application-client#29]
```
const {hits} = await request()
    .query('*sade*')
    
    .setPageSize(100)
    .search()
```

no matter what we put inside query it always return same 10 results. how to fix it

**Comment by joemcelroy** [comment]
Hi there, 

Sorry for late reply. You need to update your search application template to handle the params sent by the client and transform it into an elasticsearch query. 

See client template here: https://github.com/elastic/search-application-client#boilerplate-template
how to update template: https://www.elastic.co/guide/en/elasticsearch/reference/current/put-search-application.html

The client also has a CLI to update the template for you. See how to run this command here (https://www.elastic.co/guide/en/elasticsearch/reference/current/put-search-application.html)
